### PR TITLE
version 1.3.11

### PR DESCRIPTION
**Pull request by funkycram**
Enh: Added module label configuration - gives possibility to have a module name different for each space (FunkycraM)

The reason is that this wiki module is used for several reasons and the name "Wiki" is not all the time appropriated, depending on the space purpose.

This pull request is lacking translations for the new file `config.php` in `message` directory, only `fr` is done.

### CODE REVIEW

**Comment by buddh4** [comment]
Hmm, wouldn't it be enough to overwrite the translation?

**Comment by funkycram** [comment]
Overwriting translation would rename module for all spaces.
This pull request enable to have a custom name for each space.

**Comment by buddh4** [comment]
You are right, I'll have a look into this looks fine on first sight. Perhaps in the future a general way of renaming the context of a module would be great.

**Comment by funkycram** [comment]
I have just added a commit, as I forgot to add `use humhub\modules\calendar\permissions\ManageEntry;` in `ContainerConfigController.php`

**Comment by buddh4** [comment]
Sorry it took so long, unfortunately there was an when I resolved the conflicts, but I fixed the issue and added the same support for profiles.

**Pull request merged**
